package by.europrotocol.activity.registration

enum class RegistrationStep {
    STEP_FIRMA_INFO,
    STEP_PERSONAL_DRIVER_INFO,
    STEP_VEHICLE_DATA,
    STEP_INSURER_INFO,
    STEP_DRIVER_INFO,
    STEP_PLACE_HOLDER_DATA,
    STEP_AUTO_INFO,
    STEP_QUESTION_ACCIDENT,
    STEP_CIRCUMSTANCES_OF_AN_ACCIDENT,
    STEP_PLACE_OF_IMPACT,
    STEP_PLACE_OF_ACCIDENT,
    STEP_MY_NOTES
}